apiVersion: v1
kind: Pod
metadata:
    name: fluentd
    labels:
        app: fluentd
        tier: platform
        role: axcritical
spec:
    containers:
      - name: fluentd
        image: gcr.io/google_containers/fluentd-elasticsearch:1.17
        resources:
            limits:
                cpu: 100m
                memory: 300Mi
            requests:
                cpu: 45m
                memory: 200Mi
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: dockermnt
            mountPath: /mnt/ephemeral/docker
            readOnly: true
          - name: config
            mountPath: /etc/td-agent
            readOnly: true
    terminationGracePeriodSeconds: 30
    volumes:
      - name: varlog
        hostPath:
            path: /var/log
      - name: varlibdockercontainers
        hostPath:
            path: /var/lib/docker/containers
      - name: dockermnt
        hostPath:
          path: /mnt/ephemeral/docker
      - name: config
        hostPath:
          path: /etc/td-agent
